### ISSUE TITLE
digitizer -  behavior on touch display and mobile devices 

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender#1090]
If you use no tabs in the digitizer, the element does not behave as expected (on touch display / mobile devices). As a user of other digitizer-masks i expect, that the mask to capture the informations opens an i can start to add my infos at any place of the mask.

However, if no tabs are specified, immediately after opening the edit-mask, the first input field becomes active and the keyboard opens. This hinders the correct acquisition of data.

This can be avoided by adding tabs, even if no other tabs are used next to the first tab - However this unnecessarily enlarges the formular. This behaviour was tested with a windows convertible laptop and android smartphone.

You can test this with this open application: https://demo.mapbender.org/application/digitizer_display

"Wrong" Code : 

```
  [...] 
  formItems:
    - type: form
      children:
        - type: fieldSet
          children:
            - type: input
              title: [...]
```

<img src="https://user-images.githubusercontent.com/13517141/52724703-24395f00-2fb0-11e9-9cae-7c225e45c3f1.jpeg"  width="350" height=auto>

"Correct" Code:

```
   [...] 
  formItems:
    - type: tabs
      children:
        - type: form
          title: 'tab 1'
          css: {padding: 10px}
          children:
              - type: fieldSet
                children:
                  - type: input
                    title: [...]
        - type: form
          title: 'tab 2'
          css: {padding: 10px}
          children:
              - type: fieldSet
                children:
                  - type: input
                    title: [...]
```

<img src="https://user-images.githubusercontent.com/13517141/52724689-1c79ba80-2fb0-11e9-8025-777a4e04b09f.jpeg"  width="350" height=auto>
