### ISSUE TITLE
app/console doctrine:fixtures:load import of application fails if no screenshot folder exists in uploads-directory

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1157]
**Describe the bug**
yml-applications can be loaded via  app/console doctrine:fixtures:load

> app/console doctrine:fixtures:load --fixtures=./mapbender/src/Mapbender/CoreBundle/DataFixtures/ORM/Application/ --append

See documentation https://github.com/mapbender/mapbender-documentation/blob/master/en/installation/installation_ubuntu.rst
```
Part from yaml-File (screenshot can't be disabled or deleted - error still occurs)
parameters:
    applications:
        mapbender_user_digitizer:
            title: Mapbender Digitze Demo
            screenshot: ~
            description: Try the Mapbender Digitize Demo
```

**To Reproduce**
1. cd mapbender/
2. provice an additional ymal-Application at config/application/
3. app/console doctrine:fixtures:load --fixtures=./mapbender/src/Mapbender/CoreBundle/DataFixtures/ORM/Application/ --append
```
[UnexpectedValueException]                                                                                                                                                          
  RecursiveDirectoryIterator::__construct(/data/mapbender/demo_mapbender_org/v3.0.8/application/web/uploads/mapbender_user_digitizer): failed to open dir: No such file or directory  
```
5. When you provide the directory: import works

**Expected behavior**
Applications is loaded to Mapbender database without problem

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.7.7 and 3.0.8
