### ISSUE TITLE
role of user

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender#1221]
At the bottom of the contact information of a user you can define the role of a person. For newcomers, this is very misleading. Most users think that the permissions for the applications are given here (role-system via acls). I would suggest renaming this area or giving a hint that this is just meta-information irrelevant to mapbender.
This problem has already been criticized several times during training.

**Describe the solution you'd like**
Other name, e.g. "position in company"

**Additional context**
![Auswahl_150](https://user-images.githubusercontent.com/13517141/69172865-e77e3380-0afe-11ea-8882-9c24bd40be23.png)

**Comment by fhaefker** [comment]
Hello CharlyUnicorn,

thanks for the advice.

We have received this feature request and will discuss it during the next sprint planning.

Best Regards
Frederik

**Comment by werrolf** [comment]
Too late for FOM v3.1.11.

Label is set in translation messages as `form.profile.basic.organizationRole`.  
As a preliminary project solution, the text can be changed by dropping `translations/messages.<locale>.yml` files into `app/Resources`, or into the Resource path in any activated bundle. These files should contain the desired label texts. E.g.
```yml
## app/Resources/translations/messages.en.yml
## <YourBundle>/Resources/translations/messages.en.yml
form:
  profile:
    basic:
      organizationRole: position
```
