### ISSUE TITLE
[Frontend][Digitizer] with sidepane mode buttons: featuretable has no scrollbar

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1269]
**Describe the bug**
When you use digitizer in the sidepane with sidepane mode **buttons** the digitizer frame has no scrollbar and the feature table appears out of the frame (use a small browser window to show this)

In yaml-definition it is the mode tabs-> name: tabs 
```
parameters:
    applications:
        mapbender_user_digitizer:
            title: Mapbender Digitze Demo
            screenshot: ~
            description: ~
            published: true
            template:  Mapbender\CoreBundle\Template\Fullscreen
            regionProperties:
              - name: sidepane
                properties:
                  name: tabs
```

**To Reproduce**
1. Create an application with digitizer
2. Change the mode to tabs(german:button) for sidepane (!!! save to see the changes)
3. Open your application in a small browser window

**Expected behavior**
There should be a scrollbar in the bitton mode too

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.2

**Screenshots / Logmessage**

![sidepane_button_mode](https://user-images.githubusercontent.com/996298/98512827-3b7dad00-2267-11eb-8251-d63d6a696f08.png)

![digitizer_sidepane_button_mode](https://user-images.githubusercontent.com/996298/98512847-40426100-2267-11eb-814a-7b23bfb4adcc.png)
