### ISSUE TITLE
 [Digitizer] type select with multiple: true - can not handle multiple values

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1299]
**Describe the bug**
In digitizer you can define select boxes. You also can define  multiple: true. But with  multiple: true you can't save feature. You get an error "Notice: Array to string conversion".
The error occurs when you have a text field or an array field in your database.
```

ALTER TABLE poi add column type_array varchar[];
Update poi set type_array =string_to_array (type,',') where type is not null
Select distinct type, type_array from poi;
```

```
                                                    -
                                                        type: select
                                                        title: Type (multi and array)
                                                        multiple: true
                                                        name: type_array # or column type
                                                        mandatory: false
                                                        mandatoryText: 'Please give a name to the new object.'
                                                        infoText: 'Help: Please give a name to the new object.'                                                        
                                                        options:
                                                            A: A
                                                            B: B
                                                            C: C
                                                            D: D
                                                            E: E 
```

**To Reproduce**
1. Create a digitizer demo with multiple: true
2. Select values and try to save the object
3. See error: Object can't be saved

**Expected behavior**

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.3

**Screenshots / Logmessage**
![mb_digitizer_select_multi](https://user-images.githubusercontent.com/996298/104168100-c44acd80-53fd-11eb-876b-0df46f16b784.png)
