### ISSUE TITLE
[digitizer] type image does not work 

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1340]
**Describe the bug**
In Mapbender 3.0.8.x it was possible to define images. This does not work in 3.2.4 anymore

https://doc.mapbender.org/de/functions/editing/digitizer.html#bildanzeige-type-image

```
            -
              type: image
              name: typ
              src: 'https://demo.mapbender.org/bundles/mapbendercore/image/pin_red.png'
              enlargeImage: true
              relative: false              
              css:
                width: 30%
              infoText: 'The image will show up after saving.'
```

Reference to dynamic images depending on the column value was possible too:
```
            -
              type: image
              name: typ
              src: 'https://demo.mapbender.org/bundles/mapbendercore/image/${typ}.png'
              enlargeImage: true
              relative: false              
              css:
                width: 30%
              infoText: 'The image will show up after saving.'
```

**To Reproduce**
1. use the workshop demo https://github.com/mapbender/mapbender-workshop/blob/release/3.2/app/config/applications/mapbender_digitize_demo.yml
2. Add an image section
3. See error

**Expected behavior**
The error should be displayed

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.4
