### ISSUE TITLE
[digitizer] data-manager required selectboxes do not show mandatory text

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1427]
**Describe the bug**
In the digitizer configuration you can define mandatory fields and mandatoryText. The text is displayed for input and textArea. But not for select.

See code
https://github.com/mapbender/data-manager/blob/master/Resources/public/FormRenderer.js#L429

**To Reproduce**
1. Create an application with digitizer functionality
2. add a selectbox

```
            -
              type: select
              title: 'Type pflichtfeld'
              name: type
              required: true
              mandatoryText: 'Please give a name to the new object.'
              infoText: 'Help: Please give a name to the new object.'
              placeholder: Platzhalter
              options:
                -
                  label: 'Please select'
                  value: ''
                -
                  label: A
                  value: A
                -
                  label: B
                  value: B
```

4. save without a selection in the selectbox
5. see that the mandatory filed is highlighted, but the text is not displayed
6. Create an input and see that the mandatory text is there

```
            -
              type: input
              title: 'Name pflichtfeld'
              mandatory: true
              name: name
              mandatoryText: 'Please give a name to the poi.'
              infoText: 'Help: Please give a name to the new object.'
```

**Expected behavior**
If no selection was made for a selectbox, the mandatory text should be displayed
**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.3.1

**Screenshots / Logmessage**
If applicable, add screenshots or a logmessage from app/logs to help explain your problem.

**Additional context**
