### ISSUE TITLE
[Selfregister] password is not saved properly. Login is not possible

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1430]
**Describe the bug**
When you activate selfregister in your config.yml (your mailer has to activated, you could install sendmail). You can register from the login section. After activation of the account you can not login

config.yml
```
fom_user:
    selfregister: true
    reset_password: false
    max_reset_time: 1
    self_registration_groups: 
      - Schulung
    mail_from_address: admin@wheregroup.com
    mail_from_name: "Admin)" 
```

**To Reproduce**
1. activate rselfregister in your mapbender installation and configrue your mailer (parameters.yml)
2. go to the login and further to Register 
3. register a new account
4. You will receive a mail with a link. 
5. When you click on the link the account is activated
6.  Problem: When you try to login you fail. Your password that you chose before is not accepted

You can try here http://schulung.foss.academy/mapbender/

**Expected behavior**
After the account is activated it should be possible to login.

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: tested with 3.2.10, 3.3.1, 3.3.2
 - Database: Postgresql 
 - Browser firefox
