### ISSUE TITLE
[searchRouter] type text  data-autocomplete-using: gemeinde does not work

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1474]
**Describe the bug**
data-autocomplete-using: [column] can be used to filter the autocomplete values. It worked in 3.3.3. Does not work in 3.3.4.
- app_dev.php does not use the filter and gives back all results
- app.php runs into an error

See documentation
- https://doc.mapbender.org/en/functions/search/search_router.html#type-text

![Bildschirmfoto vom 2023-05-22 09-01-05](https://github.com/mapbender/mapbender/assets/996298/4560b00b-2663-4c92-9dfd-3eac4a208557)

Add parameter to your search to test  data-autocomplete-using

```
      attr:
        data-autocomplete: 'on'
        data-autocomplete-distinct: 'on'
        data-autocomplete-using: gemeinde
```

**Versions (please complete the following in
 - 3.3.4[e.g. 3.0.6.3]
 - Database: Postgresql
 - Browser firefox
