### ISSUE TITLE
[digitizer] required fields are not obvious from the beginning, only when you try to save you see the red boarder

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1515]
**Describe the bug**
You can define mandatory: true or requreid for mandatory fields. But the user does not see from the start that a filed is mandatory (worked in older Mapbender versions). Only when you try to save you see the red border and if defined the mandatory text. 

```
            -
              type: input
              title: Name
              name: name
              mandatoryText: 'Please give a name to the poi.'
              infoText: 'Help: Please give a name to the new object.'
              copyClipboard: true
              attr:
                placeholder: 'Please give a name to the poi.'
                required: true
```

see also https://github.com/mapbender/data-manager/blob/2.0.7/README.md#configuring-tabular-item-listing

**To Reproduce**
1. Go to your digitizer application
2. Save an object with mandatory fileds that are not filled
4. See the red boarder around the mandatory fields

**Expected behavior**
The red boarder should be there from the beginning and not only when the object is saved

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.3.5

**Screenshots / Logmessage**
![digitizer_required_save](https://github.com/mapbender/mapbender/assets/996298/98916951-7b7d-4025-a0ea-dfcc56f14d3f)
