### ISSUE TITLE
[digitizer] selectbox with multiselect and required:required does not show the red boarder if nothing is selected

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1516]
**Describe the bug**

- Selectnox can be defined as single (only one object can beselected) oder multi
- Problem: selectbox with multiselect and required:required does not show the red boarder if nothing is selected

```
            -
              type: select
              title: Type
              name: type
              infoText: 'Help: Please choose a type.'
              mandatoryText:  'Mandatory: Please choose a type.'
              attr:
                required: required
                multiple: multiple
              options:
                -
                  label: 'Please select a type...'
                  value: ''
                -
                  label: 'Type A'
                  value: A
                -
                  label: 'Type B'
                  value: B
                -
                  label: 'Type C'
                  value: C
                -
                  label: 'Type D'
                  value: D
```

see also https://github.com/mapbender/data-manager/blob/2.0.7/README.md#configuring-tabular-item-listing

**To Reproduce**
1. Define a selectbox with multiselect and required:required 
2. Save without selecting any object in the selectbox
4. See error: does not show the red boarder if nothing is selected. The foxus is set although to the field

**Expected behavior**
The mandatory filed should show the red boarder

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.3.5

**Screenshots / Logmessage**
![digitizer_multiselect](https://github.com/mapbender/mapbender/assets/996298/fa9388f3-ea9c-42ce-af92-46284d7c94c8)
