### ISSUE TITLE
digitizer shows tool-icons to edit feature-geometries even when digitizing is disabled

### ISSUE THREAD

**Issue by kartoffelfee** [mapbender/mapbender#1647]
The digitizer shows tool-icons to edit feature-geometries even when digitizing is disabled.

Expected behavior: No Tool-Icons to minipulae feature geometries, should be displayed.

see https://schulung.foss.academy/mapbender/application/mapbender_digitize_demo_db

![image](https://github.com/user-attachments/assets/42cc8bd6-e96b-4295-8583-a0fe62418f82)

digitizer yml:
```
...
  allowCreate: false
  allowDigitize: false
  toolset: {  }
  popup:
....
```
'toolset: null' or 'toolset []' has now effect, too.

whole config:
```
polygon:
  label: 'polygon digitizing 1'
  maxResults: 1500
  featureType:
    connection: geodata_db
    table: polygons
    uniqueId: gid
    geomType: polygon
    geomField: geom
    srid: 4326
    styleField: style
  allowDelete: true
  allowCustomStyle: true
  allowCancelButton: true
  allowDeleteByCancelNewGeometry: false
  allowCreate: false
  allowDigitize: false
  toolset: {  }
  popup:
    title: 'polygon test suite'
    width: 500px
  searchType: currentExtent
  tableFields:
    gid:
      label: Nr.
      width: 20%
    name:
      label: Name
      width: 80%
  formItems:
    -
      type: label
      title: 'Welcome to the digitize demo. Try the new Mapbender feature!'
    -
      type: input
      title: Name
      mandatory: true
      name: name
      mandatoryText: 'Please give a name to the new object.'
      infoText: 'Help: Please give a name to the new object.'
    -
      type: select
      title: Type
      name: type
      mandatoryText: 'Please give a type to the new object.'
      infoText: 'Help: Please give a type to the new object.'
      options:
        A: A
        B: B
        C: C
        D: D
        E: E
polygon2:
  label: 'polygon digitizing 2'
  maxResults: 1500
  featureType:
    connection: geodata_db
    table: polygons
    uniqueId: gid
    geomType: polygon
    geomField: geom
    srid: 4326
    styleField: style
  allowDelete: true
  allowCustomStyle: true
  allowCancelButton: true
  allowDeleteByCancelNewGeometry: false
  toolset:
    -
      type: moveFeature
  popup:
    title: 'polygon test suite'
    width: 500px
  searchType: currentExtent
  tableFields:
    gid:
      label: Nr.
      width: 20%
    name:
      label: Name
      width: 80%
  formItems:
    -
      type: label
      title: 'Welcome to the digitize demo. Try the new Mapbender feature!'
    -
      type: input
      title: Name
      mandatory: true
      name: name
      mandatoryText: 'Please give a name to the new object.'
      infoText: 'Help: Please give a name to the new object.'
    -
      type: select
      title: Type
      name: type
      mandatoryText: 'Please give a type to the new object.'
      infoText: 'Help: Please give a type to the new object.'
      options:
        A: A
        B: B
        C: C
        D: D
        E: E
```
