### ISSUE TITLE
[Bug] SearchRouter autocomplete uses compare type ilike-right

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1741]
**Describe the bug**

When you define an autocomplete field and connect it to another field via  data-autocomplete-using: gemeinde the connection uses compare type ilike-right as default which might give back too much data. 

```
      attr:
        data-autocomplete: 'on'
        data-autocomplete-distinct: 'on'
        data-autocomplete-using: gemeinde
```

see code: uses compare type ilike-right
- https://github.com/mapbender/mapbender/blob/master/src/Mapbender/CoreBundle/Component/SQLSearchEngine.php#L56

If you have a table with gemeinde of germany you will get back Bonn and Bonndorf for example although you selected Bonn 

**Expected behavior**
Discuss

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 4.1.2
 
**Screenshots / Logmessage**

![Image](https://github.com/user-attachments/assets/0b5a54d6-22c1-47b5-9018-cdc7f629a178)

**Additional context**

```
class: Mapbender\CoreBundle\Component\SQLSearchEngine
class_options:
  connection: geodata_db
  relation: brd.qry_gn250_p_ortslage
  attributes:
    - gid
    - name
    - gemeinde
    - hoehe_ger
    - bundesland
    - ewz_ger
  geometry_attribute: geom
form:
  gemeinde:
    type: Symfony\Component\Form\Extension\Core\Type\TextType
    options:
      label: Gemeinde
      required: false
    compare: ilike
  name:
    type: Symfony\Component\Form\Extension\Core\Type\TextType
    options:
      required: true
      label: Name
      attr:
        data-autocomplete: 'on'
        data-autocomplete-using: gemeinde
        placeholder: 'Please provide a name.'
    compare: exact
results:
  view: table
  count: true
  exportcsv: true
  headers:
    name: Name
    gemeinde: Gemeinde
    bundesland: Bundesland
    ewz_ger: Einwohner
    hoehe_ger: Höhe
  callback:
    event: click
    options:
      buffer: null
      minScale: 500
      maxScale: 1000
  styleMap:
    default:
      strokeColor: '#00ff00'
      strokeWidth: 4
      strokeOpacity: 1
      fillOpacity: 0
      pointRadius: 6
    select:
      strokeColor: '#ff00ff'
      fillColor: '#ff00ff'
      fillOpacity: 0.8
      pointRadius: 6
    temporary:
      strokeColor: '#0000ff'
      fillColor: '#0000ff'
      fillOpacity: 1
      pointRadius: 10
```
