### ISSUE TITLE
sidepane status close does not open the sidepane after click on the button

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#487]
If you would like to create an application with sidepane closed you can change your twig and delete the class sidePaneOpened.

`  <div id="templateWrapper" class="templateWrapper">`

Siedpane will be closed on start of the application. Problem is, that it does not open when you click the button +

![mb3_sidepane](https://cloud.githubusercontent.com/assets/996298/23711983/ac04300c-0421-11e7-87b1-3ca4e9a259c1.png)

**Comment by eSlider** [comment]
@astroidex, full screen template side pane behaviour is improved. There is no need to create own one. Just configurate as folow.

# YAML Configuration

- `align`: **[left|right]** - Side pane aligment. Default: `left`
- `closed`: **[true|false]** - Side pane initiale state. Default: `false`
- `width`: **[px|em|%]** - Side pane width. This value is inline-css and injected in a Twig-Template. Default: `350px`


## Example
```yaml
parameters:
  applications:
      test-app:
          template:  Mapbender\CoreBundle\Template\Fullscreen
          regionProperties:
              - name: sidepane
                properties:
                  name: accordion
                  label: test
                  align: right # right|left
                  width: "500px" 
                  closed: true
```

# Commits

FOM: https://github.com/mapbender/fom/commit/8d1bf7e356e3e40408a867fba9f4fce196c362d3
Mapbender: https://github.com/mapbender/mapbender/commit/ca3ecfb086b3a35938d4c8a21cf288c71bfb9a2a
