### ISSUE TITLE
Ruler new immediate: true is true in all existing application if not defined

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#538]
* with version 3.0.6 we have the new parameter  immediate: true for ruler
* it did not exist in 3.0.5
* in all applications from 3.0.5 this element is assumed true, although it is not checked in addministration - this is a strange behaviour

```
                    lineruler:
                        title: Distance
                        tooltip: 'ruler'
                        class: Mapbender\CoreBundle\Element\Ruler
                        target: map
                        type: line
                        immediate: true
```
