### ISSUE TITLE
Provide a console command to export and import applications

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#592]
- app/console mapbender:list:application
- app/console mapbender:export:application
- app/console mapbender:import:application

(or mapbender:applications:... ;-))

Parameter:
- f file
- m mapping file
- s with source

Background: Export application from test system, import in productive system. Problem: WMS in Testsystem is http://test-wmsserver/. In Productive-System: http://prod-wmsserver/. Therefore the mapping to say: I already have defined the WMS, you don't have to create the datasource but you can directly connect your layersets and instances to the existing WMS in prod. Condition: The structure of the WMS should be the same (like they have to be in staging/test/prod environments).

File: The YAML file. We only support one format.

Mapping file: example

```yaml
[...]
datasource:
    wms:
        source:
            title-id: "mein_prod_wms_strassen"
        target:
            title-id: "mein_prod_wms_strassen"
[...]
```

With source: Epxort the complete source definition. Import it, so that the source is created on the prod.

Open points/to be defined
- ACL (export/import userstructure)
- Application ID
- Layerset ID
- Layerset Instance ID
- Reusable Layersetinstances (export/import reusable layersetinstances)
