### ISSUE TITLE
DB based WMS not showing up in layertree

### ISSUE THREAD

**Issue by DeEgge** [mapbender/mapbender#769]
A WMS that is correctly set up through 'data sources' and added to an application is not showing up in the layertree. This is a database application.

It does, however, if it is configured for a yaml-application, e.g.

```yaml
basemap_at:
    class: Mapbender\WmsBundle\Entity\WmsInstance
    title: Basemap.at
    url: https://wms2016.wheregroup.com/mapproxy/bev/service
    version: 1.1.1
    layers:
        10: { name: basemap_layer, title : Basemap, visible: true }
    info_format: text/html
    visible: true
    format: image/png
    transparent: true
    tiled: true
```

And, it can also be added through the WMS loader. 

The WMS also does show up correctly in a simple OpenLayers script and QGIS.

To reproduce this, go to https://sandbox.mapbender.org/application/ck_basemap_at. Then try to load https://wms2016.wheregroup.com/mapproxy/bev/service?VERSION=1.1.1&REQUEST=GetCapabilities&SERVICE=WMS with WMS loader.

As the WMS can be added via YAML config and WMS loader, I'm guessing there's something wrong with the database entries. Loading the applications throws no error whatsoever.

**How was this WMS created?**

This was originally a [WMTS](https://www.basemap.at/#sec-zugang), that is parsed by Mapproxy to create a WMS. Config:

```yaml
services:
  demo:
  wms:
    srs: ['EPSG:25833','EPSG:4326','EPSG:3857','EPSG:25832']
    image_formats: ['image/png', 'image/jpeg']
    md:
      # metadata used in capabilities documents
      title: Basemap.at
      abstract: basemap.at ist eine internetfähige Grundkarte von Österreich
      contact:
        person:
        position:
        organization:
        address:
        city:
        postcode:
        country: Austria
        phone: +49(0)000-000-000
        fax:
        email:
      access_constraints:
        n/a
      fees: 'None'

layers:
  - name: basemap_layer
    title: Basemap
    sources: [basemap_cache]

caches:
  basemap_cache:
    format: image/png
    request_format: image/png
    meta_size: [1,1]
    meta_buffer: 0
    grids: [webmercator]
    sources: [wmts_tile_source]
    cache:
      type: sqlite
      directory: /data/mapproxy/cache_data

sources:
  wmts_tile_source:
    type: tile
    url: https://maps.wien.gv.at/basemap/geolandbasemap/normal/google3857/%(z)s/%(y)s/%(x)s.png
    transparent: true
    grid: webmercator
    coverage:
      bbox: [977650, 5838030, 1913530, 6281290]
      srs: 'EPSG:3857'

grids:
    webmercator:
        base: GLOBAL_WEBMERCATOR
        origin: 'nw'
```
