### ISSUE TITLE
[Documentation][Digitizer] - add information about filter and events

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender#804]
Missing informations: 
* how to filter
* how to use events

```
point_digitizer:
  label: 'Digitizer'
  featureType:
    connection: search_db
    [..]
    filter: 'year > 2000'
    events:
      onBeforeSave: '$feature->setAttribute("user_name", $user->getUsername());'
```
