### ISSUE TITLE
Integrate coordinate utility in mapbender.yml Demo application

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#810]
Files and applications:
- application/app/config/applications/mapbender_user.yml: Mapbender Demo Map / mapbender_user
- application/app/config/applications/mapbender_user_basic.yml: Mapbender Demo Map / basic mapbender_user_basic

Example code:

``` yaml
coordinatesutility:
                        title: 'Koordinaten Utility'
                        class: Mapbender\CoordinatesUtilityBundle\Element\CoordinatesUtility
                        type: element
                        target: map
                        srsList:
                            -
                                name: 'EPSG:31466'
                                title: '31466'
                            -
                                name: 'EPSG:31468'
                                title: '31468'
                            -
                                name: 'EPSG:25833'
                                title: '25832'
                            -
                                name: 'EPSG:4326'
                                title: '4326'
                        addMapSrsList: true
```

TODOS:

- [ ] integrate in the 2 yml applications
- [ ] Document and verify yml-possibilties
- [ ] Check transfer into database via command: `app/console doctrine:fixtures:load --fixtures=./mapbender/src/Mapbender/CoreBundle/DataFixtures/ORM/Application/ --append`
