### ISSUE TITLE
Image Export - Wrong display of digitizer-features with label

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender#857]
If you define a labeling for your features in the digitizer and try to export it to an png/jpeg file the features are displayed diffrently, e.g. if you define a white point with black label, then you get a red label in the output. 
Regardless of the defined feature style and other labeling parameters, the red label always comes out.  

Test with following style definition for points (works with the column "name" ): 

```
  styles:
    default:
      strokeWidth: 2
      strokeColor: '#000000'
      fillColor: '#ffffff'
      fillOpacity: 1
      pointRadius: 10
      label: '${name}'
      labelOutlineColor: '#ffffff'
      fontColor: '#000000'
      fontFamily: 'Verdana, Tahoma, Geneva, sans-serif;'
      fontWeight: bold
      labelXOffset: 0
      labelYOffset: 25
    select:
      strokeWidth: 2
      strokeColor: '#fd00ff'
      fillColor: '#ffffff'
      fillOpacity: 1
      pointRadius: 10
      label: '${name}'
      labelOutlineColor: '#ffffff'
      fontColor: '#000000'
      fontFamily: 'Verdana, Tahoma, Geneva, sans-serif;'
      fontWeight: bold
      labelXOffset: 0
      labelYOffset: 25
```

**Comment by CharlyUnicorn** [comment]
If you define an image for the display your features in the digitizer and try to export it to an png/jpeg file the features are not displayed. 

Test with following style definition for points: 

  styles:
    default:
      externalGraphic: 'https://cdn3.iconfinder.com/data/icons/free-icons-3/512/cat_5.png'
      graphicHeight: 50
      graphicOpacity: 1
    selected:
      externalGraphic: 'https://icon-icons.com/icons2/554/PNG/512/cat_6_icon-icons.com_53579.png'
      graphicHeight: 70
      graphicOpacity: 1

**Comment by astroidex** [comment]
* @CharlyUnicorn are they exported with the normal print?

**Comment by CharlyUnicorn** [comment]
@astroidex nice question: you can see the label is in the pdf-print, but it is alway a level lower than the feature, so you see only a part of the label, because the feature covers the letters. if you use the graphics, then you can only see the default style in the print (green circles). 

@LazerTiberius perhaps this should go into another ticket?

**Comment by werrolf** [comment]
Print / export support for `externalGraphic` style on vector features has recently been added and will be in the upcoming 3.0.8.1 release.

**Comment by astroidex** [comment]
Correct application of font colors should already be working since 3.0.8. -> tested: works with 3.0.8.1

Print / export support for externalGraphic style
* tested with 3.0.8.1. Does not work. Extermal graphic is not displayed in print

Tested with:

```
                                styles:
                                  default:
                                    label: '${name}'
                                    labelOutlineColor: '#ffffff'
                                    fontColor: '#ff00ff'
                                    fontFamily: 'Verdana, Tahoma, Geneva, sans-serif;'
                                    fontWeight: bold
                                    labelXOffset: 0
                                    labelYOffset: 25
                                    externalGraphic: 'https://cdn3.iconfinder.com/data/icons/free-icons-3/512/cat_5.png'
                                    graphicHeight: 50
                                    graphicOpacity: 1
                                  selected:
                                    externalGraphic: 'https://icon-icons.com/icons2/554/PNG/512/cat_6_icon-icons.com_53579.png'
                                    graphicHeight: 70
                                    graphicOpacity: 1  
```

**Comment by GeOSMRob** [comment]
In the current print client, all layers are checked for their style parameters. The fixAssetPath function of ImageExport checks the URL string on the found path to the asset folder.

If no path is found, then the layer is sorted out for printing and you get a warning in the console.

- https://github.com/mapbender/mapbender/blob/release/3.0.7/src/Mapbender/PrintBundle/Resources/public/mapbender.element.imageExport.js#L330

**Comment by astroidex** [comment]
**Label position export**
* label export is done but offset is ignored

**Export graphic to print solved for internal graphics**
Thanks @GeOSMRob for the information. Works fine with the following definition. 
* had to define graphicHeight and graphicWidth
* still in the pdf output is the default circle style this had to be eliminated with fillOpacity and strokeOpacity

```
                                styles:
                                  default:
                                    label: '${name}'
                                    labelOutlineColor: '#ffffff'
                                    fontColor: '#ff00ff'
                                    fontFamily: 'Verdana, Tahoma, Geneva, sans-serif;'
                                    fontWeight: bold
                                    labelXOffset: 0
                                    labelYOffset: 25
                                    externalGraphic: 'http://localhost/mapbender3081/bundles/mapbendercore/image/cat_5.png'
                                    graphicHeight: 50
                                    graphicWidth: 50
                                    graphicOpacity: 1
                                    fillOpacity: 0
                                    strokeOpacity: 0
```

![cat](https://user-images.githubusercontent.com/996298/57914705-76c83700-788f-11e9-9734-0a0515c2ee06.png)
